mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls'))
]

users/urls.py
from django.urls import path
from users.views import register_user_view, login_user_view, logout_user_view, dashboard_view

app_name='users'
urlpatterns = [
    path('', register_user_view, name='register_user'),
    path('login-user/', login_user_view, name='login_user'),
    path('logout-user/', logout_user_view, name='logout_user'),
    path('dashboard/', dashboard_view, name='dashboard')
]

users/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models

# class UserManager(BaseUserManager):
#     def _create_user(self, email, password, **extra_fields):
#         if not email:
#             raise ValueError('The Email field must be set')
#         email = self.normalize_email(email)
#         user = self.model(email=email, **extra_fields)
#         user.set_password(password)
#         user.save(using=self._db)
#         return user
# def create_user(self, email, password=None, **extra_fields):
#         extra_fields.setdefault('is_staff', False)
#         extra_fields.setdefault('is_superuser', False)
#         return self._create_user(email, password, **extra_fields)

# def create_superuser(self, email, password=None, **extra_fields):
#         extra_fields.setdefault('is_staff', True)
#         extra_fields.setdefault('is_superuser', True)
#         if extra_fields.get('is_staff') is not True:
#             raise ValueError('Superuser must have is_staff=True.')
#         if extra_fields.get('is_superuser') is not True:
#             raise ValueError('Superuser must have is_superuser=True.')
#         return self._create_user(email, password, **extra_fields)

class User(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=150)
    country = models.CharField(max_length=100)
    nationality = models.CharField(max_length=100)
    mobile = models.CharField(max_length=15)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'country', 'nationality', 'mobile'] 

    # objects = UserManager()
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='custom_user_user_permissions',
        blank=True
    )
    groups = models.ManyToManyField(
        'auth.Group',
        related_name='custom_user_groups',
        blank=True
    )

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from users.models import User
import re

class RegisterUserForm(forms.ModelForm):
    confirm_password = forms.CharField(
        label='Confirm Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    class Meta:
        model = User
        fields = (
            'name',
            'email',
            'country',
            'nationality',
            'mobile',
            'password',
            'confirm_password'
        )
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'country': forms.TextInput(attrs={'class': 'form-control'}),
            'nationality': forms.TextInput(attrs={'class': 'form-control'}),
            'mobile': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
        }
    
    def clean_name(self):
        name=self.cleaned_data.get('name')
        if not name:
            raise ValidationError("Name cannot be empty")
        if len(name) < 2:
            raise ValidationError("Name must be at least 2 characters long")
        return name

    def clean_mobile(self):
        mobile=self.cleaned_data.get('mobile')
        pattern = re.compile(r'^\d{10}$')
        if not re.match(pattern, mobile):
            raise ValidationError("Invalid mobile number. Please enter a 10-digit number.")
        return mobile
        
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        if password != confirm_password:
            raise ValidationError("Passwords do not match")
        return cleaned_data
        
class LoginUserForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from users.forms import RegisterUserForm, LoginUserForm

def register_user_view(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            password = form.cleaned_data['password']
            user = form.save(commit=False)
            user.set_password(password)
            user.save()
            messages.success(request, f'User created for {name} successfully')
            return redirect('users:login_user')
        else:
            return render(request, 'users/register_user.html', {'form':form})
    else:
        form = RegisterUserForm()
        context = {
            'form':form
        }
    return render(request, 'users/register_user.html', context)

def login_user_view(request):
    
    if request.method == "POST":
        form = LoginUserForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f'Welcome, {user.name}!')
                if request.user.is_authenticated:
                    return redirect('users:dashboard')
            else:
                messages.warning(request, 'Invalid email or password.')
    else:
        form = LoginUserForm()

    return render(request, 'users/login_user.html', {'form': form})


def logout_user_view(request):
    logout(request)
    return redirect('users:login_user')

def dashboard_view(request):
    return render(request,'users/dashboard.html')

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Welcome to mysite{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block extra_css %}
    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#" style="font-size: 24px; font-weight: bold; color: #333; text-decoration: none;">Mysite</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout_user' %}">Logout</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login_user' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_user' %}">Register</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container mt-5">
    {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
      {% block content %}
      {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% block extra_scripts %}
    {% endblock %}
  </body>
</html>

templates/users/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block title %}Mysite | Welcome to Dashboard page{% endblock %}
{% block extra_css %}
<style>
    body {
        font-family: Arial, sans-serif;
        line-height: 1.6;
        margin: 0;
        padding: 0;
    }
    header {
        background-color: #333;
        color: #fff;
        padding: 20px;
        text-align: center;
    }
    .container {
        max-width: 800px;
        margin: auto;
        padding: 20px;
    }
</style>
{% endblock %}

{% block content %}
<header>
    <h1>Welcome to Your Dashboard</h1>
</header>
<div class="container">
    <article>
        <h2>Overview</h2>
        <p>This is your dashboard page. You can customize this page to display useful information or functionality for your users.</p>
        <p>For example, you could display recent activities, important notifications, or provide links to frequently used features of your application.</p>
    </article>
</div>
{% endblock %}

templates/users/login_user.html
{% extends "base.html" %}
{% load static %}
{% block title %}Mysite | Login{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class="card">
      <div class="card-body">
        <form id="loginForm" action="{% url 'users:login_user' %}" method="post" novalidate>
          {% csrf_token %}
          {{form.as_p}}
          <input type="submit" class="btn btn-primary w-100">
        </form>
      </div>
    </div>
  </div>
</div>

<script>
  document.getElementById("loginForm").addEventListener("submit", function(event) {
    var email = document.getElementById("id_email").value.trim();
    var password = document.getElementById("id_password").value.trim();

    if (email === "" || password === "") {
      event.preventDefault(); 
      alert("Please fill in all fields.");
    }
    var emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      event.preventDefault();
      alert("Please enter a valid email address.");
    }
  });
</script>

{% endblock %}

templates/users/register_user.html
{% extends "base.html" %}
{% load static %}
{% block title %}Mysite | Registration{% endblock %}
{% block extra_css %}
<style>
  li{
   color: red!important;
 }
</style>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class="card">
      <div class="card-body">
        <form id="registrationForm" action="{% url 'users:register_user' %}" method="post" novalidate>
          {% csrf_token %}
          <!-- {{form.as_p}} -->
          {{form.name.label}}
          {{form.name}}
          {% if form.name.errors %}
          {% for error in form.name.errors %}
          <p class="text-danger">{{error}}</p>
          {% endfor %}
          {% endif %}
          {{form.email.label}}
          {{form.email}}
          {% if form.email.errors %}
          {% for error in form.email.errors %}
          <p class="text-danger">{{error}}</p>
          {% endfor %}
          {% endif %}
          {{form.mobile.label}}
          {{form.mobile}}
          {% if form.mobile.errors %}
          {% for error in form.mobile.errors %}
          <p class="text-danger">{{error}}</p>
          {% endfor %}
          {% endif %}
          {{form.country.label}}
          {{form.country}}
          {% if form.country.errors %}
          {% for error in form.country.errors %}
          <p class="text-danger">{{error}}</p>
          {% endfor %}
          {% endif %}
          {{form.nationality.label}}
          {{form.nationality}}
          {% if form.nationality.errors %}
          {% for error in form.nationality.errors %}
          <p class="text-danger">{{error}}</p>
          {% endfor %}
          {% endif %}
          {{form.password.label}}
          {{form.password}}
          {% if form.password.errors %}
          {% for error in form.password.errors %}
          <p class="text-danger">{{error}}</p>
          {% endfor %}
          {% endif %}
          {{form.confirm_password.label}}
          {{form.confirm_password}}
          {% if form.confirm_password.errors %}
          {% for error in form.confirm_password.errors %}
          <p class="text-danger">{{error}}</p>
          {% endfor %}
          {% endif %}
          <input type="submit" class="btn btn-primary w-100 mt-4">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block extra_scripts %}
<script src="{% static 'js/validate_register.js' %}"></script>
{% endblock %}